### ISSUE TITLE
Please add a `LICENSE` file to this repo

### ISSUE THREAD

**Issue by mbrukman** [cloudinary-community/photobox#15]
First, thank you for creating and sharing this project with us! Looks really cool.

It looks like the `package.json` file is already specifying the MIT license for the project:

https://github.com/cloudinary-community/photobox/blob/9b9784550d3d5139ee7f21298ecfed29e07b8a1b/package.json#L5

What would also be helpful is to include a `LICENSE` file with the contents of the license: https://choosealicense.com/licenses/mit/ to make this easier to discover, and GitHub will helpfully link to it and add a badge to the repo so that it's obvious at a glance that this is under the MIT license: 
![image](https://github.com/cloudinary-community/photobox/assets/4074659/4f436d51-aef5-4d0f-8579-a22163131980)

Thanks!

**Comment by colbyfayock** [comment]
thanks, missed adding it, but added! https://github.com/cloudinary-community/photobox/blob/main/LICENSE
